---
title: "`r params$report_title`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    code_folding: hide
params:
  report_title: "Meta-analysis of age groups"
  report_author: "Tamas Szabo"
---

## Setup

```{r results="hide", message=FALSE, warning=FALSE}
library(dplyr)
library(tibble)
library(stringr)
library(survminer)
library(ggplot2)

filter <- dplyr::filter
select <- dplyr::select
arrange <- dplyr::arrange

set.seed(1234)

color_names <- c("#E64B35B2", "#4DBBD5B2", "#00A087B2", "#3C5488B2", "#F39B7FB2", "#8491B4B2")
```

## Risk ratio in age groups

```{r}
N <- 200

rr_test_data <- 101 %>%
  seq(., . + N-1) %>%
  paste("S", ., sep="_") %>%
  enframe(value="Subject") %>%
  mutate(
    Age         = sample(1:90, n(), replace=TRUE),
    Sex         = sample(c("f", "m"), n(), replace=TRUE),
    Group       = sample(c("A", "B"), n(), replace=TRUE),
    long_surv   = sample(150:500, n(), replace=TRUE),
    short_surv  = sample(50:250, n(), replace=TRUE),
    long_event  = sample(1:3, n(), replace=TRUE),
    short_event = sample(1:4, n(), replace=TRUE),
    Time        = ifelse(Group == "A", long_surv, short_surv),
    Event       = case_when(
      Group == "A" & long_event > 2 ~ 1,
      Group == "B" & short_event > 1 ~ 1,
      TRUE ~ 0
    )
  ) %>%
  select(-long_surv, -short_surv, long_event, short_event)

head(rr_test_data)
```

