---
title: "`r params$report_title`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    code_folding: hide
params:
  report_title: "Meta-analysis of survival studies"
  report_author: "Tamas Szabo"
---

## Setup

```{r results="hide", message=FALSE, warning=FALSE}
library(dplyr)
library(tibble)
library(stringr)
library(purrr)
library(survival)
library(survminer)
library(epitools)
library(PHEindicatormethods)
library(forestplot)
library(ggplot2)
library(DT)

filter <- dplyr::filter
select <- dplyr::select
arrange <- dplyr::arrange

set.seed(1234)

color_names <- c("#E64B35B2", "#4DBBD5B2", "#00A087B2", "#3C5488B2", "#F39B7FB2", "#8491B4B2")
```

```{r}
calculate_groupwise_rr <- function(df) {
  df %>%
    select(n.risk, cum.n.event, Group) %>%
    column_to_rownames("Group") %>%
    t() %>%
    epitab(method="riskratio") %>%
    .$tab %>%
    data.frame() %>%
    mutate(
      Sex    = unique(x$Sex),
      Cohort = unique(x$Cohort)
    ) %>%
    .[2,] %>%
    rownames_to_column("Comparison")
}
```

## Construction of toy data

```{r}
N <- 500
max_age <- 90

main_tab <- 101 %>%
  seq(., . + N-1) %>%
  paste("S", ., sep="_") %>%
  enframe(value="Subject") %>%
  mutate(
    Age         = sample(1:max_age, n(), replace=TRUE),
    Sex         = sample(c("f", "m"), n(), replace=TRUE),
    Group       = sample(c("A", "B"), n(), replace=TRUE),
    long_surv   = sample(150:500, n(), replace=TRUE),
    short_surv  = sample(50:250, n(), replace=TRUE),
    long_event  = sample(1:3, n(), replace=TRUE),
    short_event = sample(1:4, n(), replace=TRUE),
    Time        = ifelse(Group == "A" & Age < 50, long_surv, short_surv),
    Event       = case_when(
      Group == "A" & long_surv > 450 ~ 0,
      Group == "B" & short_surv > 230 ~ 0,
      Group == "A" & long_event < 2 ~ 0,
      Group == "B" & short_event < 2 ~ 0,
      TRUE ~ 1
    ),
    Cohort = cut_width(Age, 10, boundary=0, labels=paste(seq(0, max_age-10, 10), seq(10, 90, 10), sep="-"))
  ) %>%
  select(-long_surv, -short_surv, long_event, short_event)

head(main_tab)
```

## Survival curves

```{r}
fit <- survfit(Surv(Time, Event) ~ Group + Sex, data = main_tab)
```

```{r}
# Base R

plot(
  fit, xlab = "Time", ylab = "Survival"
)
```

```{r}
ggsurvplot(
  fit, data = main_tab,
  palette = "npg", legend.title = "",
  legend.labs = c("Group A (f)", "Group A (m)", "Group B (f)", "Group B (m)")
)
```

```{r}
toy_risk_table <- surv_summary(fit, data = main_tab)

datatable(toy_risk_table)
```

## Hazard ratios

```{r}
main_tab %>%
  coxph(Surv(Time, Event) ~ Group + Sex + Age, data = .) %>%
  ggforest(data = main_tab)
```

## Logrank test

```{r}
logrank_result <- survdiff(Surv(Time, Event) ~ Group + Sex + Age, data = main_tab)

logrank_result
```